import streamlit as st
from myCountryModelPackages.Economic_Research import *
from myCountryModelPackages.sqlTableRetrieve import *
st.title("Economic Research Analysis")
st.write( \
    "This page is intended to create a sandbox where you can modify the Economic Research table.  \
    You can modify the weightings for each country industry.  Then run the country model, analyze results \
    before publishing to the database.  Once you are satisfied, then the Economic Research will be published and the Country Model \
    for that report will be published as well.  Currently, this is the raw Economic Research table that is derived from the Economic Spreadsheet \
    To make this easier to manipulate, we will create data entry similar or exactly the same as the spreadsheet and perform all the conversions \
    behind the scenes.")

st.write( "")
st.write("The Economic Research table can be modified and will not be written back to the data base.")
st.write( "")
st.write("Filters will be added so you can drill down to the specific Region, Industry, etc.")

# db_cxcn = st.session_state['db_cxcn_economic_research']
base_year = st.session_state['base_year']
economic_data = CountryEconomicResearch(base_year)
economic_research = economic_data.get_VBA_Generated_EconomicTable()
economic_research_compare = economic_data.get_Economic_Comparison()

economic_research_data = Economic_Research_Create(base_year)
country_industrial_gdp_fraction = economic_research_data.get_industrial_gdp_fraction()
country_industrial_automation_degree = economic_research_data.get_industrial_automation_degree()
gdp_x_country = economic_research_data.get_gdp_x_country()

if 'base_year' in st.session_state:
    #st.write("Economic Research Generated by VBA Loader")
    #st.data_editor(economic_research,disabled=("Country", "Region","BaseYear","Industry"))
    st.write("GDP by Country from Reuters upload")
    st.write(gdp_x_country)
    #st.write("GDP Fraction - new table basically column #9 in Excel Economic Table.")
    #st.write(country_industrial_gdp_fraction)
    st.write("Automation Degree is the Industry weight by Country and the Master Data table automation degree")
    #st.write(country_industrial_automation_degree)
    st.write(economic_research_compare)

